const create_CodeBlock = require('./cb_create_CodeBlock')

// blockLanguage, blockTitle, dayNumber, correctBlock, timidBlock, delusionalBlock, correctCode


const initializeCodeBlocks = () => {
	create_CodeBlock('JavaScript', 'Declaring Variables', 0, 'const a = 1\nconst b = \'string\'\nconst c = a + b', 'const _ = 1\nconst b = _string_\n_____ c = a _ b', 'var a = 1\nconst b = string\nconst c = a & b', 'const a = 1Æconst b = \'string\'Æconst c = a + b')
	create_CodeBlock('JavaScript', 'Declaring Variables', 0, 'let myVariable = \'\'\nmyVariable = \'Not blank\'\nmyVariable = 100', 'let __________ = \'\'\nmyVariable _ \'Not blank\'\nmy___iable = 100', 'vars myVariable = \'\'\nmyVariable != \'Not blank\'\nmyVar = 100', 'let myVariable = \'\'ÆmyVariable = \'Not blank\'ÆmyVariable = 100')
	create_CodeBlock('JavaScript', 'Declaring Arrays', 0, 'let myArray = []\nmyArray.push(a)\nmyArray.push(c)\nconsole.log(myArray)', '___ myArray = []\nmyArray.____(a)\n_______.push(c)\n_______.log(myArray)', 'let myArray = {}\nmyArray.push[a]\nconst myArray.push(c)\nconsole.frog(myArray)', 'let myArray = []ÆmyArray.push(a)ÆmyArray.push(c)Æconsole.log(myArray)')
	create_CodeBlock('JavaScript', 'Declaring Functions', 0, 'function myFunction (arg1, arg2) {\n var str = arg1\n var newStr = arg1 + arg2\n return newStr\n}', '________ myFunction (arg1, arg2) {\n ___ str _ arg1\n var newStr = ____ + arg2\n return ___Str\n}', 'function myFunction (arg1 arg2) {\n var str = arrg1\n newStr = arg1 += arg2\n reurn newStr\n}', 'function myFunction (arg1, arg2) {Æ var str = arg1Æ var newStr = arg1 + arg2Æ return newStrÆ}')
	create_CodeBlock('HTML', 'HTML Page Strucure', 0, '<html>\n <head>\n\n </head>\n <body>\n\n </body>\n</html>', '<html>\n <____>\n\n </____>\n <body>\n\n </body>\n</____>', '<http>\n <shed>\n\n </hear>\n <bawdy>\n\n </shoddy>\n</hello>', '<html>Æ <head>ÆÆ </head>Æ <body>ÆÆ </body>Æ</html>')
	create_CodeBlock('CSS', 'CSS Button Styling', 0, 'button {\n background-color: black;\n color: #FFF;\n}', 'button {\n background-_____: black;\n color: ____;\n}', 'button {\n body-bgcolor: #67hrs;\n color: #67hrs;\n}', 'button {Æ background-color: black;Æ color: #FFF;Æ}')
	create_CodeBlock('JavaScript', 'Arrow Functions', 1, 'const myFunction = () => {\n const str1 = \'some text\'\n console.log\nstr1.length)\n}', 'const myFunction = __ __ {\n _____ str1 = \'some text\'\n console.___\nstr1.length)\n}', 'var myFunction = (is perfect) = {\n str1 = some text\n console.slog\nstr1.lenth)\n}', 'const myFunction = () => {Æ const str1 = \'some text\'Æ console.logÆstr1.length)Æ}')
	create_CodeBlock('Command Line', 'Command Line Alias', 1, 'alias gpom="git push origin master"', 'alias gpom="git push ______ master"', 'alies gpom="git push origin faster"', 'alias gpom="git push origin master"')
	create_CodeBlock('Command Line', 'Command Line Function', 1, 'copyFiles() {\n  cp -r ~/workspace/ ~/workspace/backup\n}', 'copyFiles__ {\n  cp __ ~/workspace/ ~/workspace/backup\n}', 'copyFlies() {\n  copy -r ~/workspace/ /workspace/backup\n}', 'copyFiles() {Æ    cp -r ~/workspace/ ~/workspace/backupÆ}')
	create_CodeBlock('Command Line', 'Command Line', 1, 'mkdir NewDirectory', 'mk___ NewDirectory', 'makedir NewDirectory', 'mkdir NewDirectory')
	create_CodeBlock('Command Line', 'Node Package Manager', 1, 'npm init\nnpm install --save-dev browserify', '___ init\nnpm install --save-___ browserify', 'npm start\nnpm install --crave-dev browserify', 'npm initÆnpm install --save-dev browserify')
	create_CodeBlock('Command Line', 'Initialize New GitHub Repo', 2, 'git init\ngit add .\ngit commit -m "message"\ngit remote add origin https://github.com/userName/repo\ngit push -u origin master', '___ init\ngit add _\ngit commit __ "message"\ngit ______ add origin https://github.com/userName/repo\ngit push -u origin ______', 'sith init\nsith add .\nsith commit -m "message"\nsith remote add origin https://sithumb.com/userName/repo\nsith push -u seed matrix', 'git initÆgit add .Ægit commit -m "message"Ægit remote add origin https://github.com/userName/repoÆgit push -u origin master')
	create_CodeBlock('JavaScript', 'Printing to the DOM', 2, 'const titleText = \'Welcome to My Page\'\nconst parent = document.getElementById(\'titleSpot\')\nconst title = document.createElement(\'h1\')\ntitle.textContent = titleText\nparent.appendChild(title)', '_____ titleText = \'Welcome to My Page\'\nconst parent = document.get_______ById(\'titleSpot\')\nconst title = document.______Element(\'h1\')\ntitle.text_______ = titleText\nparent.append_____(title)', 'var titleText = \'Welcome to My Page\'\nlet parent = document.getElement(\'titleSpot\')\nconstant title = window.createElement(\'h1\')\ntitle.innerHTML = titleText\nparent.addChild(title)', 'const titleText = \'Welcome to My Page\'Æconst parent = document.getElementById(\'titleSpot\')Æconst title = document.createElement(\'h1\')Ætitle.textContent = titleTextÆparent.appendChild(title)')
	

}

module.exports = initializeCodeBlocks